# Generated by Django 2.2.1 on 2019-06-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('openid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('money', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
