# Generated by Django 2.2.1 on 2019-06-13 09:27

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makemoney', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='surveys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100, null=True)),
                ('numOfQuestions', models.IntegerField()),
                ('reward', models.DecimalField(decimal_places=2, max_digits=8)),
                ('questions', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict), size=None)),
                ('idOfReleaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makemoney.Users')),
            ],
        ),
    ]
