# Generated by Django 2.2.1 on 2019-06-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makemoney', '0004_users_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='stop',
            field=models.BooleanField(default=False),
        ),
    ]
