# Generated by Django 2.2.1 on 2019-06-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makemoney', '0005_auto_20190613_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='stop',
        ),
        migrations.AddField(
            model_name='surveys',
            name='stop',
            field=models.BooleanField(default=False),
        ),
    ]
