# Generated by Django 2.2.1 on 2019-06-14 09:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makemoney', '0008_auto_20190614_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='idOfResumeAnswered',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
