# Generated by Django 2.2.1 on 2019-06-14 15:23

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makemoney', '0009_users_idofresumeanswered'),
    ]

    operations = [
        migrations.CreateModel(
            name='resumes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('idOfReleaser', models.CharField(max_length=100)),
                ('reward', models.DecimalField(decimal_places=2, max_digits=8)),
                ('questions', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict), size=None)),
                ('stop', models.BooleanField(default=False)),
            ],
        ),
    ]
