# Generated by Django 2.2.1 on 2019-06-16 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makemoney', '0011_answerofresume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='answerOfresume',
        ),
    ]
