# Generated by Django 2.2.1 on 2019-06-16 04:52

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makemoney', '0012_delete_answerofresume'),
    ]

    operations = [
        migrations.CreateModel(
            name='answerOfresume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('idOfReleaser', models.CharField(max_length=100)),
                ('idOfResume', models.IntegerField()),
                ('questions', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict), size=None)),
                ('nameOfUser', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
